web/router.ex
defmodule Madscribes2.Router do
  use Madscribes2.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Madscribes2 do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/registrations", RegistrationController, only: [:new, :create]

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

    resources "/stories", StoryController
    resources "/sentences", SentenceController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Madscribes2 do
  #   pipe_through :api
  # end
end

web/models/story.ex
defmodule Madscribes2.Story do
  use Madscribes2.Web, :model

  schema "stories" do
    field :title, :string
    field :body, :string
    field :writing_period, :integer
    field :voting_period, :integer
    field :started_at, Ecto.DateTime
    field :rounds, :integer

    belongs_to :user, Madscribes2.User
    has_many :subscriptions, Madscribes2.Subscription
    has_many :sentences, Madscribes2.Sentence

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :user_id, :body, :writing_period, :voting_period, :started_at, :rounds])
    |> validate_required([:title, :user_id, :body, :writing_period, :voting_period, :started_at, :rounds])
  end

  def subscription_count do
    # Repo.aggregate(self.subscriptions, :count, :id)
    5
  end
end

web/controllers/story_controller.ex
defmodule Madscribes2.StoryController do
  use Madscribes2.Web, :controller

  alias Madscribes2.Story
  alias Madscribes2.Sentence

  def index(conn, _params) do
    stories = Repo.preload(Repo.all(Story), [:user, :subscriptions])
    render(conn, "index.html", stories: stories)
  end

  def new(conn, _params) do
    changeset = Story.changeset(%Story{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"story" => story_params}) do
    changeset = Story.changeset(%Story{}, story_params)

    case Repo.insert(changeset) do
      {:ok, _story} ->
        conn
        |> put_flash(:info, "Story created successfully.")
        |> redirect(to: story_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    sentence_changeset = Sentence.changeset(%Sentence{}, %{"story_id" => id})

    story = Repo.preload(Repo.get!(Story, id), [:user, :subscriptions, sentences: :user])
    render(conn, "show.html", story: story, sentence_changeset: sentence_changeset)
  end

  def edit(conn, %{"id" => id}) do
    story = Repo.get!(Story, id)
    changeset = Story.changeset(story)
    render(conn, "edit.html", story: story, changeset: changeset)
  end

  def update(conn, %{"id" => id, "story" => story_params}) do
    story = Repo.get!(Story, id)
    changeset = Story.changeset(story, story_params)

    case Repo.update(changeset) do
      {:ok, story} ->
        conn
        |> put_flash(:info, "Story updated successfully.")
        |> redirect(to: story_path(conn, :show, story))
      {:error, changeset} ->
        render(conn, "edit.html", story: story, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    story = Repo.get!(Story, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(story)

    conn
    |> put_flash(:info, "Story deleted successfully.")
    |> redirect(to: story_path(conn, :index))
  end
end

web/views/story_view.ex
defmodule Madscribes2.StoryView do
  use Madscribes2.Web, :view
end

web/templates/story/edit.html.eex
<h2>Edit story</h2>

<%= render "form.html", changeset: @changeset,
                        action: story_path(@conn, :update, @story) %>

<%= link "Back", to: story_path(@conn, :index) %>

web/templates/story/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :user_id, class: "control-label" %>
    <%= number_input f, :user_id, class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= label f, :writing_period, class: "control-label" %>
    <%= number_input f, :writing_period, class: "form-control" %>
    <%= error_tag f, :writing_period %>
  </div>

  <div class="form-group">
    <%= label f, :voting_period, class: "control-label" %>
    <%= number_input f, :voting_period, class: "form-control" %>
    <%= error_tag f, :voting_period %>
  </div>

  <div class="form-group">
    <%= label f, :started_at, class: "control-label" %>
    <%= datetime_select f, :started_at, class: "form-control" %>
    <%= error_tag f, :started_at %>
  </div>

  <div class="form-group">
    <%= label f, :rounds, class: "control-label" %>
    <%= number_input f, :rounds, class: "form-control" %>
    <%= error_tag f, :rounds %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/story/index.html.eex
<h2>Listing stories</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Body</th>
      <th>Writing period</th>
      <th>Voting period</th>
      <th>Started at</th>
      <th>Rounds</th>
      <th>Subscriptions</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for story <- @stories do %>
    <tr>
      <td><%= story.title %></td>
      <td><%= story.user.email %></td>
      <td><%= story.body %></td>
      <td><%= story.writing_period %></td>
      <td><%= story.voting_period %></td>
      <td><%= story.started_at %></td>
      <td><%= story.rounds %></td>
      <td><%= Enum.count(story.subscriptions) %></td>

      <td class="text-right">
        <%= link "Show", to: story_path(@conn, :show, story), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: story_path(@conn, :edit, story), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: story_path(@conn, :delete, story), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New story", to: story_path(@conn, :new) %>

web/templates/story/new.html.eex
<h2>New story</h2>

<%= render "form.html", changeset: @changeset,
                        action: story_path(@conn, :create) %>

<%= link "Back", to: story_path(@conn, :index) %>

web/templates/story/show.html.eex
<h2>Show story</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @story.title %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @story.user_id %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @story.body %>
  </li>

  <li>
    <strong>Writing period:</strong>
    <%= @story.writing_period %>
  </li>

  <li>
    <strong>Voting period:</strong>
    <%= @story.voting_period %>
  </li>

  <li>
    <strong>Started at:</strong>
    <%= @story.started_at %>
  </li>

  <li>
    <strong>Rounds:</strong>
    <%= @story.rounds %>
  </li>

</ul>

<%= link "Edit", to: story_path(@conn, :edit, @story) %>
<%= link "Back", to: story_path(@conn, :index) %>

<div class="page-header">
  <h1>
    <%= @story.title %><small> by <%= @story.user.email %></small>
  </h1>

  <div class="well">
    <h4>
      <%= @story.body %>
    </h4>
  </div>
</div>

<div class="col-sm-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Winning Sentences</h3>
    </div>
    <div class="panel-body">
      <div class="sentence_container">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Round</th>
                <th>Author</th>
                <th>Votes</th>
                <th>Sentence</th>
              </tr>
            </thead>
            <tbody>
              <%= for sentence <- @story.sentences do %>
                  <tr>
                    <td><%= sentence.round %></td>
                    <td><%= sentence.user.email %></td>
                    <td><%= sentence.votes %></td>
                    <td><%= sentence.body %></td>
                  </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-sm-12">
  <div class="well action_well">
    <%= form_for @sentence_changeset, sentence_path(@conn, :create), fn f -> %>
      <h3>Submit a Sentence</h3>
      <div class="form-group">
        <%= label f, :body, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= text_input f, :body, class: "form-control" %>
        </div>
        <%= error_tag f, :title %>
        <%= hidden_input f, :story_id %>
      </div>
      <div class="actions form-group">
        <div class="col-sm-offset-1 col-sm-11">
          <%= submit "Submit", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>