web/router.ex
defmodule Madscribes2.Router do
  use Madscribes2.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Madscribes2 do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/registrations", RegistrationController, only: [:new, :create]

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

    resources "/stories", StoryController
    resources "/sentences", SentenceController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Madscribes2 do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="banner">
  <img src="<%= static_path(@conn, "/images/header.jpg") %>">
</div>

<div class="jumbotron">
  <h2>Welcome to Madscribes</h2>
    <ul>
      <li>Each round you submit a sentence</li>
      <li>Everyone votes on the sentence they like the best</li>
      <li>The winning sentence is added to the story</li>
      <li>You recieve a point for each vote</li>
    </ol>
</div>

<div class="col-sm-12">
  <ul class="chat-list">
    <div class="messages"></div>
  </ul>
  <hr>
  <div class="form-inline">
    <input class="chat-input form-control" placeholder="<%= chat_placeholder(@current_user) %>" <%= disable_input?(@current_user) %>></input>
    <button class="btn btn-primary" <%= disable_input?(@current_user) %>>Submit</button>
  </div>
</div>

<%= if @current_user do %>
  <%= tag :meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", @current_user.id) %>
<% end %>

<%= link "Stories", to: story_path(@conn, :index) %>